[tool.pytest.ini_options]
pythonpath = [".", "tests"]
filterwarnings = [
    "ignore:This process .* is multi-threaded, use of fork\\(\\) may lead to deadlocks in the child:DeprecationWarning",
]

[tool.pylint.MASTER]
max-line-length = 120
disable = ["too-many-arguments", "too-many-positional-arguments","c-extension-no-member", "no-member", "import-error", "missing-class-docstring", "duplicate-code", "protected-access", "global-statement","too-many-instance-attributes", "fixme"]
good-names = ["x","k","y","i","dx","dy","x1","y1","a","b"]

